name: Upload Images to Cloudinary

on:
  push:
    branches:
      - main # or your chosen branch

jobs:
  upload_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or the version you need

      - name: Install dependencies
        run: npm install

      - name: Upload images to Cloudinary
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: node upload-images.mjs
